version: '3.2'

services:

  postgres:
    container_name: pg
    image: postgres:10.0-alpine
    networks:
      - i-adopt-network
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_DB: iadopt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@iadopt.com'
      PGADMIN_DEFAULT_PASSWORD: '123'
    networks:
      - i-adopt-network
    depends_on:
      - postgres

networks:
  i-adopt-network:
    driver: bridge

volumes:
  data:
